version: '3'
services:
  github:
    image: node:14.15.4
    ports:
      - 8080:8080
    command: bash -c "npm install && npm run serve"
    container_name: github
    working_dir: /src
    volumes:
      - "../../.:/src"
    environment:
      HOST: 0.0.0.0
      APP_ENV: dev
      TERM: xterm-256color
